language: python
python:
  - 3.6
install:
  - make install
script:
  - make test

notifications:
           email:
             recipients:
               issaquebaloi@gmailcom
               on_sucess:change
               on_failure: always
               
